# Generated by Django 4.1.7 on 2023-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'КРИТИЧЕСКИЙ'), (1, 'ОШИБКА'), (2, 'ПРЕДУПРЕЖДЕНИЕ'), (3, 'ИНФОРМАТИВНЫЙ')])),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
