# Generated by Django 4.1.7 on 2023-03-24 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 24, 11, 48, 13, 596369, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
