# Generated by Django 4.1.7 on 2023-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_logfile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
