# Generated by Django 4.1.7 on 2023-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_log_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='module',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(upload_to='log_files/%Y/%m/%d/'),
        ),
    ]
