# Generated by Django 4.1.7 on 2023-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_log_module_alter_logfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-id'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterField(
            model_name='log',
            name='module',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
