# Generated by Django 4.1.7 on 2023-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_log_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.IntegerField(choices=[(0, 'Неназначен'), (1, 'Дебаг'), (2, 'ИНФОРМАТИВНЫЙ'), (3, 'ПРЕДУПРЕЖДЕНИЕ'), (4, 'ОШИБКА'), (5, 'КРИТИЧЕСКИЙ')]),
        ),
    ]
