# Generated by Django 4.1.7 on 2023-03-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_log_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logs.log')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия пользователей',
                'ordering': ['-id'],
            },
            bases=('logs.log',),
        ),
        migrations.CreateModel(
            name='TraceBack',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logs.log')),
                ('is_corrected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Трасировку',
                'verbose_name_plural': 'Трасировки',
                'ordering': ['-id'],
            },
            bases=('logs.log',),
        ),
    ]
