# Generated by Django 4.1.7 on 2023-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_operation_traceback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfile',
            options={'ordering': ['-id'], 'verbose_name': 'Лог-файл', 'verbose_name_plural': 'Лог-файлы'},
        ),
        migrations.AddField(
            model_name='logfile',
            name='source_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
