# Generated by Django 4.1.7 on 2023-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_logfile_options_logfile_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='source_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
