# Generated by Django 4.1.7 on 2023-03-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_log_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='corrected_at',
        ),
        migrations.AddField(
            model_name='traceback',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
